### ISSUE TITLE
this.parent.group is not a function

### ISSUE THREAD

**Issue by AnReZa** [svgdotjs/svg.select.js#59]
When calling the (now renamed) selectize function, I get the error from the title everywhere I try.

The following code worked with the 2.7.x branch, but it doesn't anymore after renaming the method to selectize:

```
img.select(':not(image):not(defs)').each(function (i, children) {
    allElements.push(this);
    makeElementInteractive(this, false);
});
```

What can I do?

> svg.select.min.js:1 Uncaught TypeError: this.parent.group is not a function
>     at i.init (svg.select.min.js:1)
>     at Svg.selectize (svg.select.min.js:1)
>     at Object.openAnnotationEditor (diagnosis.js:918)
>     at Object.eval (eval at parseBindingsString (knockout.js:74), <anonymous>:3:148)
>     at HTMLDivElement.<anonymous> (knockout.js:100)
>     at HTMLDivElement.dispatch (jquery-3.3.1.min.js:2)
>     at HTMLDivElement.y.handle (jquery-3.3.1.min.js:2)

**Comment by Fuzzyma** [comment]
Are you mixing things up here? `select()` takes a css selector and gives you a Set. The `selectize` method draws a selection around the element you call it on. It is something completely different. Why would you rename something in the first place if it was working?

**Comment by AnReZa** [comment]
@Fuzzyma After the update to 3.x, my former code doesn't work anymore. So I researched a little bit and found a note, that the select method was renamed to selectize.

> Uncaught TypeError: img.select is not a function
>     at Object.openAnnotationEditor (diagnosis.js:804)
>     at Object.eval (eval at parseBindingsString (knockout.js:74), <anonymous>:3:148)
>     at HTMLDivElement.<anonymous> (knockout.js:100)
>     at HTMLDivElement.dispatch (jquery-3.3.1.min.js:2)
>     at HTMLDivElement.y.handle (jquery-3.3.1.min.js:2)

```javascript
openAnnotationEditor: function (d, e) {
	e.stopPropagation();

	vm.data.modeData = d;
	vm.currentMode(modes.annotationEditor);

	let canvas = document.getElementById('ap-canvas');
	let canvasCoords = canvas.getBoundingClientRect();
	let img = SVG(canvas);
	let bgImg = img.select('image').first(); // That's the problematic line
	let allElements = [];
	let selectedElements = [];
	let currCtrl = null;
	let currCtrlFor = null;
	let currStream = null;
	
	// ...
}
```

**Comment by Fuzzyma** [comment]
No, the select method of the library was never renamed. This plugin (this repo) had a nameclash with the core an thats why we renamed the method of this plugin.

In 3.0 `select()` returns a List which is basically a fancy array. So if you want the first element just access it with `[0]`

**Comment by AnReZa** [comment]
@Fuzzyma As you can see, the error message states that select is not a function. So there must be something wrong. Have you removed `.select()` from the SVG object?

**Comment by Fuzzyma** [comment]
my fault right there. Ofc yes. select was renamed to `find()`. There is also the single case equivalent `findOne()` which is what you are looking for. So you can just go and use `ìmg.findOne('image')`
